[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  blynkkk/Blynk
  bblanchon/ArduinoJson@^6.20

board_build.filesystem = spiffs
upload_speed = 921600
